// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AddUserBookOperation           OperationName = "AddUserBook"
	GetUserBookOperation           OperationName = "GetUserBook"
	GetUserBooksOperation          OperationName = "GetUserBooks"
	RemoveUserBookOperation        OperationName = "RemoveUserBook"
	UpdateReadingProgressOperation OperationName = "UpdateReadingProgress"
)
