// Code generated by ogen, DO NOT EDIT.
package api

type AddUserBookRes interface {
	addUserBookRes()
}

type GetUserBookRes interface {
	getUserBookRes()
}

type RemoveUserBookRes interface {
	removeUserBookRes()
}

type UpdateReadingProgressRes interface {
	updateReadingProgressRes()
}
