// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *Error) setDefaults() {
	{
		val := string("")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateReadingProgressReq) setDefaults() {
	{
		val := int(1)
		s.Page = val
	}
}
